-- Add missing columns to client_users table
ALTER TABLE client_users
ADD COLUMN IF NOT EXISTS email VARCHAR,
ADD COLUMN IF NOT EXISTS firstName VARCHAR,
ADD COLUMN IF NOT EXISTS lastName VARCHAR,
ADD COLUMN IF NOT EXISTS phone VARCHAR,
ADD COLUMN IF NOT EXISTS invitationToken VARCHAR,
ADD COLUMN IF NOT EXISTS invitationExpiresAt TIMESTAMP,
ADD COLUMN IF NOT EXISTS deactivatedAt TIMESTAMP;