apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "true"
spec:
  rules:
  - host: api.soc-compliance.com
    http:
      paths:
      # Auth Service
      - path: /api/v1/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 3000
      # Client Service
      - path: /api/v1/clients
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 3001
      # Audit Service
      - path: /api/v1/audits
        pathType: Prefix
        backend:
          service:
            name: audit-service
            port:
              number: 3002
      # Evidence Service
      - path: /api/v1/evidence
        pathType: Prefix
        backend:
          service:
            name: evidence-service
            port:
              number: 3003
      # Policy Service
      - path: /api/v1/policies
        pathType: Prefix
        backend:
          service:
            name: policy-service
            port:
              number: 3004
      # Control Service
      - path: /api/v1/controls
        pathType: Prefix
        backend:
          service:
            name: control-service
            port:
              number: 3005
      # Notification Service (WebSocket)
      - path: /api/v1/notifications
        pathType: Prefix
        backend:
          service:
            name: notification-service
            port:
              number: 3006
      # Reporting Service
      - path: /api/v1/reports
        pathType: Prefix
        backend:
          service:
            name: reporting-service
            port:
              number: 3007
      # Integration Service
      - path: /api/v1/integrations
        pathType: Prefix
        backend:
          service:
            name: integration-service
            port:
              number: 3008
      # AI Service
      - path: /api/v1/ai
        pathType: Prefix
        backend:
          service:
            name: ai-service
            port:
              number: 3010
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting
plugin: rate-limiting
config:
  minute: 100
  hour: 10000
  policy: local
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
plugin: cors
config:
  origins:
  - "*"
  methods:
  - GET
  - HEAD
  - PUT
  - PATCH
  - POST
  - DELETE
  - OPTIONS
  headers:
  - Accept
  - Accept-Version
  - Content-Length
  - Content-MD5
  - Content-Type
  - Date
  - X-Auth-Token
  - Authorization
  exposed_headers:
  - X-Auth-Token
  credentials: true
  max_age: 3600
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-auth
plugin: jwt
config:
  key_claim_name: iss
  secret_is_base64: false
  anonymous: ""
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer
plugin: request-transformer
config:
  add:
    headers:
    - x-request-id:$(uuid)
    - x-forwarded-prefix:/api/v1