module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/test'],
  testMatch: ['**/*.spec.ts', '**/*.test.ts'],
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.spec.json',
      },
    ],
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@shared/(.*)$': '<rootDir>/../../shared/$1',
    '^typeorm$': '<rootDir>/src/__mocks__/typeorm.ts',
    '^@nestjs/typeorm$': '<rootDir>/src/__mocks__/typeorm.ts',
    '^@nestjs/elasticsearch$': '<rootDir>/src/__mocks__/@nestjs/elasticsearch.ts',
    '^@nestjs/axios$': '<rootDir>/src/__mocks__/@nestjs/axios.ts',
    '^@nestjs/cache-manager$': '<rootDir>/src/__mocks__/@nestjs/cache-manager.ts',
    '^@nestjs/throttler$': '<rootDir>/src/__mocks__/@nestjs/throttler.ts',
    '^.*/sanitization\\.util$': '<rootDir>/src/shared/utils/__mocks__/sanitization.util.ts',
    '^sanitize-html$': '<rootDir>/src/__mocks__/sanitize-html.ts',
    '^@soc-compliance/monitoring$': '<rootDir>/src/__mocks__/@soc-compliance/monitoring.js',
  },
  moduleDirectories: ['node_modules', '<rootDir>/../../node_modules'],
  setupFilesAfterEnv: ['<rootDir>/test/jest-setup.ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.spec.ts',
    '!src/**/*.interface.ts',
    '!src/**/index.ts',
    '!src/main.ts',
  ],
  coverageDirectory: '../coverage',
  testTimeout: 30000,
  modulePathIgnorePatterns: ['<rootDir>/dist/'],
};
