groups:
  - name: secrets_management
    interval: 30s
    rules:
      # Secret access failures
      - alert: SecretsHighFailureRate
        expr: rate(secrets_access_total{result="failure"}[5m]) / rate(secrets_access_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High secrets access failure rate on {{ $labels.service }}"
          description: "Secrets access failure rate is above 10% for service {{ $labels.service }} provider {{ $labels.provider }}."

      # Provider health
      - alert: SecretsProviderDown
        expr: secrets_provider_health_status == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Secrets provider {{ $labels.provider }} is down"
          description: "Secrets provider {{ $labels.provider }} on {{ $labels.endpoint }} has been unhealthy for more than 1 minute."

      - alert: SecretsProviderSlowResponse
        expr: histogram_quantile(0.95, rate(secrets_provider_response_time_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow response from secrets provider {{ $labels.provider }}"
          description: "95th percentile response time for provider {{ $labels.provider }} is above 5 seconds."

      # Secret rotation alerts
      - alert: SecretsRotationFailure
        expr: rate(secrets_rotation_total{result="failure"}[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Secret rotation failure on {{ $labels.service }}"
          description: "Secret rotation failed for provider {{ $labels.provider }} secret {{ $labels.secret_name }}."

      - alert: SecretsRotationDue
        expr: secrets_rotation_due_count > 5
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Multiple secrets due for rotation"
          description: "{{ $value }} secrets are due for rotation on provider {{ $labels.provider }}."

      - alert: SecretsExpired
        expr: secrets_expired_count > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Expired secrets detected"
          description: "{{ $value }} secrets have expired on provider {{ $labels.provider }}."

      # Cache performance
      - alert: SecretsCacheLowHitRatio
        expr: rate(secrets_cache_operations_total{operation="hit"}[5m]) / rate(secrets_cache_operations_total{operation=~"hit|miss"}[5m]) < 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low secrets cache hit ratio"
          description: "Secrets cache hit ratio is below 50% for service {{ $labels.service }}."

      - alert: SecretsCacheHighErrorRate
        expr: rate(secrets_cache_operations_total{result="failure"}[5m]) / rate(secrets_cache_operations_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High secrets cache error rate"
          description: "Secrets cache error rate is above 5% for service {{ $labels.service }}."

      # Security violations
      - alert: SecretsSecurityViolation
        expr: rate(secrets_security_violations_total{severity=~"high|critical"}[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High severity security violation in secrets management"
          description: "{{ $labels.severity }} security violation of type {{ $labels.violation_type }} detected in service {{ $labels.service }}."

      - alert: SecretsRateLimitViolations
        expr: rate(secrets_access_rate_limit_violations[5m]) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High rate of secrets access rate limit violations"
          description: "More than 5 rate limit violations per second for secrets access."

      # Circuit breaker alerts
      - alert: SecretsCircuitBreakerOpen
        expr: secrets_circuit_breaker_state == 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Secrets circuit breaker is open"
          description: "Circuit breaker {{ $labels.circuit_name }} for provider {{ $labels.provider }} has been open for more than 5 minutes."

      - alert: SecretsCircuitBreakerTrips
        expr: rate(secrets_circuit_breaker_trips_total[10m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Frequent circuit breaker trips"
          description: "Circuit breaker {{ $labels.circuit_name }} for provider {{ $labels.provider }} is tripping frequently."

      # Audit and compliance
      - alert: SecretsAuditEventsMissing
        expr: time() - max(secrets_audit_events_total) > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Missing secrets audit events"
          description: "No secrets audit events received for more than 5 minutes."

      - alert: SecretsCriticalAuditEvents
        expr: rate(secrets_audit_events_total{severity="critical"}[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Critical secrets audit event"
          description: "Critical audit event of type {{ $labels.event_type }} detected in secrets management."

  - name: secrets_performance
    interval: 1m
    rules:
      # Performance degradation
      - alert: SecretsSlowAccess
        expr: histogram_quantile(0.95, rate(secrets_access_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow secrets access performance"
          description: "95th percentile secrets access time is above 2 seconds for provider {{ $labels.provider }}."

      - alert: SecretsSlowRotation
        expr: histogram_quantile(0.95, rate(secrets_rotation_duration_seconds_bucket[5m])) > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow secrets rotation performance"
          description: "95th percentile secrets rotation time is above 5 minutes for provider {{ $labels.provider }}."

      # Resource usage
      - alert: SecretsCacheMemoryHigh
        expr: secrets_cache_size_bytes > 1e9  # 1GB
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High secrets cache memory usage"
          description: "Secrets cache is using more than 1GB of memory in service {{ $labels.service }}."

      - alert: SecretsCacheEntriesHigh
        expr: secrets_cache_entries_count > 10000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High number of secrets cache entries"
          description: "Secrets cache has more than 10,000 entries in service {{ $labels.service }}."

  - name: secrets_compliance
    interval: 2m
    rules:
      # Compliance monitoring
      - alert: SecretsComplianceViolation
        expr: secrets_security_violations_total{severity="critical"} > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Secrets compliance violation"
          description: "Critical compliance violation detected in secrets management: {{ $labels.violation_type }}."

      - alert: SecretsUnauthorizedAccess
        expr: rate(secrets_access_total{result="failure"}[5m]) > 1 and on() rate(secrets_security_violations_total{violation_type="unauthorized_access"}[5m]) > 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Potential unauthorized secrets access attempt"
          description: "Multiple failed access attempts combined with unauthorized access violations detected."

      - alert: SecretsAnomalousActivity
        expr: |
          (
            rate(secrets_access_total[5m]) > 
            avg_over_time(rate(secrets_access_total[5m])[1h:5m]) * 3
          ) and (
            rate(secrets_access_total{result="failure"}[5m]) > 
            avg_over_time(rate(secrets_access_total{result="failure"}[5m])[1h:5m]) * 2
          )
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Anomalous secrets access activity"
          description: "Detected unusual patterns in secrets access: high volume with increased failures."